;;; Defines custom keybinds
(keymap-global-set "C-j" 'backward-char)
(keymap-global-set "C-;" 'forward-char)
(keymap-global-set "C-k" 'next-line)
(keymap-global-set "C-l" 'previous-line)
(keymap-global-set "C-p" 'electric-newline-and-maybe-indent)
(keymap-global-set "C-f" 'kill-line)
(keymap-global-set "C-n" 'recenter-top-bottom)
(keymap-global-set "M-p" 'default-indent-new-line)
(keymap-global-set "M-f" 'kill-sentence)
(keymap-global-set "M-'" 'dabbrev-expand)
(keymap-global-set "M-k" 'forward-word)
(keymap-global-set "M-j" 'backward-word)
(keymap-global-set "M-/" 'comment-dwim)

